[Interface]
PrivateKey = cNb7vK3pQ9LmR2sT8uW1xY4zA6bC0dE5fG7hI9jK2M=
Address = 172.16.0.2/32
DNS = 1.1.1.1
MTU = 1280
Jc = 4
Jmin = 40
Jmax = 70
H1 = 1
H2 = 2
H3 = 3
H4 = 4

[Peer]
PublicKey = bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = example.invalid:51820
