package com.personal.chatui.ui

object Routes {
    const val Home = "home"
    const val Settings = "settings"
    const val Connect = "connect"
    const val Images = "images"
    const val Library = "library"
    const val Projects = "projects"
    const val Remote = "remote"
    const val Scheduled = "scheduled"
    const val Plugins = "plugins"
    const val Search = "search"
    const val Personalization = "personalization"
    const val Memory = "memory"
    const val Workspace = "workspace"
    const val Plan = "plan"
    const val Usage = "usage"
    const val Parental = "parental"
    const val Email = "email"
    const val Age = "age"
    const val Appearance = "appearance"
    const val Accent = "accent"
    const val General = "general"
    const val Notifications = "notifications"
    const val Voice = "voice"
    const val Wellbeing = "wellbeing"
    const val Security = "security"
    const val Storage = "storage"
    const val Privacy = "privacy"
    const val Data = "data"
    const val Ads = "ads"
    const val Bug = "bug"
    const val About = "about"
}
