[package]
name = "tlottie"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
name = "tlottie"
crate-type = ["rlib", "cdylib"]

[[bin]]
name = "tlottie-cli"
path = "src/cli/main.rs"
required-features = ["cli"]

[features]
default = ["cpu", "std"]
cpu = []
no-std = ["dep:hashbrown", "dep:dlmalloc"]
std = []
cli = ["cpu", "std"]
c-api = ["cpu"]
wasm = ["cpu"]

[dependencies]
hashbrown = { version = "0.15", default-features = false, features = ["default-hasher", "inline-more"], optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
dlmalloc = { version = "0.2.14", default-features = false, features = ["global"], optional = true }

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
indexing_slicing = "deny"
string_slice = "deny"
fallible_impl_from = "deny"
unreachable = "deny"

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[profile.release]
opt-level = 3
debug = false
lto = "fat"
codegen-units = 1

[profile.release-size]
inherits = "release"
opt-level = "z"
strip = "symbols"

[profile.release-nostd]
inherits = "release"
panic = "abort"
