package fun.nursultan.client.modules;

import fun.nursultan.client.module.Category;
import fun.nursultan.client.module.Module;
import fun.nursultan.client.modules.combat.AimAssist;
import fun.nursultan.client.modules.combat.AttackAura;
import fun.nursultan.client.modules.combat.AutoExplosion;
import fun.nursultan.client.modules.combat.ItemRelease;
import fun.nursultan.client.modules.combat.NoSlotChange;
import fun.nursultan.client.modules.combat.NoVelocity;
import fun.nursultan.client.modules.combat.SprintReset;
import fun.nursultan.client.modules.combat.TapeMouse;
import fun.nursultan.client.modules.combat.TriggerBot;
import fun.nursultan.client.modules.combat.WebTrap;
import fun.nursultan.client.modules.misc.DeathCoords;
import fun.nursultan.client.modules.movement.AirStuck;
import fun.nursultan.client.modules.movement.AutoJump;
import fun.nursultan.client.modules.movement.EdgeJump;
import fun.nursultan.client.modules.movement.Flight;
import fun.nursultan.client.modules.movement.NoPush;
import fun.nursultan.client.modules.movement.NoSlow;
import fun.nursultan.client.modules.movement.NoWeb;
import fun.nursultan.client.modules.movement.ScreenWalk;
import fun.nursultan.client.modules.movement.Speed;
import fun.nursultan.client.modules.movement.Sprint;
import fun.nursultan.client.modules.movement.SuperFirework;
import fun.nursultan.client.modules.movement.Timer;
import fun.nursultan.client.modules.movement.WallClimb;
import fun.nursultan.client.modules.player.AntiAFK;
import fun.nursultan.client.modules.player.AutoArmor;
import fun.nursultan.client.modules.player.AutoEat;
import fun.nursultan.client.modules.player.AutoFish;
import fun.nursultan.client.modules.player.AutoLeave;
import fun.nursultan.client.modules.player.AutoPearl;
import fun.nursultan.client.modules.player.AutoRespawn;
import fun.nursultan.client.modules.player.AutoTool;
import fun.nursultan.client.modules.player.AutoTotem;
import fun.nursultan.client.modules.player.AvoidCollision;
import fun.nursultan.client.modules.player.ChestStealer;
import fun.nursultan.client.modules.player.FastExp;
import fun.nursultan.client.modules.player.NoDelay;
import fun.nursultan.client.modules.player.Scaffold;
import fun.nursultan.client.modules.visual.EntityESP;
import fun.nursultan.client.modules.visual.Gamma;
import fun.nursultan.client.modules.visual.SeeInvisible;
import fun.nursultan.client.modules.visual.TargetEsp;
import fun.nursultan.client.modules.visual.TimeChanger;
import java.util.List;

/** Registers all 109 restored UM modules. Ported classes replace DumpModule stubs. */
public final class GeneratedModules {
    public static void register(List<Module> modules) {
        modules.add(new AttackAura());
        modules.add(new AimAssist());
        modules.add(new TriggerBot());
        modules.add(new NoVelocity());
        modules.add(new DumpModule("antibot", "AntiBot", Category.COMBAT, "", "KDFzREm.UU", 23, new String[] {"no-bot-interaction"}));
        modules.add(new AutoExplosion());
        modules.add(new DumpModule("autoswap", "AutoSwap", Category.COMBAT, "base", "KDFzREm.sY", 55, new String[] {"swap-key", "first-item", "second-item", "log-swapped-item", "sunrise-runes", "any-food"}));
        modules.add(new DumpModule("backtrack", "Backtrack", Category.COMBAT, "tools", "KDFzREm.UP", 52, new String[] {"hold-after-attack"}));
        modules.add(new ItemRelease());
        modules.add(new DumpModule("nofrienddamage", "NoFriendDamage", Category.COMBAT, "", "KDFzREm.UE", 18, new String[] {}));
        modules.add(new NoSlotChange());
        modules.add(new SprintReset());
        modules.add(new TapeMouse());
        modules.add(new WebTrap());
        modules.add(new AirStuck());
        modules.add(new AutoJump());
        modules.add(new EdgeJump());
        modules.add(new DumpModule("elytratarget", "ElytraTarget", Category.MOVEMENT, "base", "KDFzREm.Ps", 37, new String[] {"chase-distance", "overtake-distance", "timing-firework-use", "bind-firework-use", "firework-use", "none-firework-use", "auto-firework-use", "delay-ticks", "manual-hotkey"}));
        modules.add(new Flight());
        modules.add(new DumpModule("freecamera", "FreeCamera", Category.MOVEMENT, "tools", "KDFzREm.PN", 39, new String[] {"speed-xz", "speed-y", "walk-by-click", "show-camera-position"}));
        modules.add(new NoPush());
        modules.add(new NoSlow());
        modules.add(new NoWeb());
        modules.add(new ScreenWalk());
        modules.add(new Speed());
        modules.add(new DumpModule("spearboost", "SpearBoost", Category.MOVEMENT, "tools", "KDFzREm.PM", 43, new String[] {"auto-jump", "boost-key"}));
        modules.add(new Sprint());
        modules.add(new SuperFirework());
        modules.add(new Timer());
        modules.add(new WallClimb());
        modules.add(new DumpModule("windhop", "WindHop", Category.MOVEMENT, "tools", "KDFzREm.PU", 36, new String[] {"auto-jump", "jump-key", "combo-key"}));
        modules.add(new AntiAFK());
        modules.add(new DumpModule("autoaccept", "AutoAccept", Category.PLAYER, "auto", "KDFzREm.Pq", 39, new String[] {"teleport-request", "command-duel-request", "clan-invite-request", "friends-accept-only"}));
        modules.add(new AutoArmor());
        modules.add(new DumpModule("autoauth", "AutoAuth", Category.PLAYER, "auto", "KDFzREm.sT", 29, new String[] {"open-path"}));
        modules.add(new DumpModule("autodripstone", "AutoDripstone", Category.PLAYER, "auto", "KDFzREm.PV", 25, new String[] {}));
        modules.add(new AutoEat());
        modules.add(new AutoFish());
        modules.add(new DumpModule("autojoin", "AutoJoin", Category.PLAYER, "auto", "KDFzREm.WC", 25, new String[] {"spooky-time-duels", "really-world"}));
        modules.add(new AutoLeave());
        modules.add(new AutoPearl());
        modules.add(new DumpModule("autopotion", "AutoPotion", Category.PLAYER, "auto", "KDFzREm.Pa", 65, new String[] {"speed-potion", "strength-potion", "fire-resistance-potion", "healing-potion", "heal-health", "heal-key", "hotbar-only", "only-in-pvp", "disable-after-throw", "exclude-donate-potions"}));
        modules.add(new DumpModule("autoreconnect", "AutoReconnect", Category.PLAYER, "auto", "KDFzREm.PA", 26, new String[] {"auto-enable-auto-leave"}));
        modules.add(new AutoRespawn());
        modules.add(new AutoTool());
        modules.add(new AutoTotem());
        modules.add(new AvoidCollision());
        modules.add(new DumpModule("blink", "Blink", Category.PLAYER, "base", "KDFzREm.PD", 38, new String[] {"release-packets-on-hit", "render-server-position", "render-color", "auto-release-packets", "release-packets-ticks"}));
        modules.add(new ChestStealer());
        modules.add(new FastExp());
        modules.add(new DumpModule("lockslots", "LockSlots", Category.PLAYER, "base", "KDFzREm.Pr", 32, new String[] {"from-inventory"}));
        modules.add(new NoDelay());
        modules.add(new DumpModule("noentitytrace", "NoEntityTrace", Category.PLAYER, "base", "KDFzREm.sN", 17, new String[] {"only-while-breaking"}));
        modules.add(new DumpModule("nointeract", "NoInteract", Category.PLAYER, "base", "KDFzREm.Ty", 59, new String[] {"aura-only", "pvp-only", "dont-place-orbs", "block-interact", "note-block", "enchant-tables", "brewing-stands", "crafting-tables", "entity-interact", "armor-stand"}));
        modules.add(new DumpModule("noserverrotation", "NoServerRotation", Category.PLAYER, "base", "KDFzREm.sy", 22, new String[] {}));
        modules.add(new DumpModule("nuker", "Nuker", Category.PLAYER, "base", "KDFzREm.sL", 40, new String[] {"break-only-allowed-blocks", "break-only-in-selection", "height-range"}));
        modules.add(new DumpModule("quickuse", "QuickUse", Category.PLAYER, "base", "KDFzREm.TL", 32, new String[] {"golden-apple", "enchanted-golden-apple", "bottle-of-exp", "instant-damage", "instant-health"}));
        modules.add(new Scaffold());
        modules.add(new DumpModule("arrows", "Arrows", Category.VISUAL, "screen", "KDFzREm.TQ", 40, new String[] {}));
        modules.add(new DumpModule("aspectratio", "AspectRatio", Category.VISUAL, "screen", "KDFzREm.Tm", 29, new String[] {"aspect-ratio", "custom-ratio"}));
        modules.add(new DumpModule("blockesp", "BlockESP", Category.VISUAL, "world", "KDFzREm.TH", 66, new String[] {"delta-mode"}));
        modules.add(new DumpModule("cooldowns", "Cooldowns", Category.VISUAL, "", "KDFzREm.jo", 28, new String[] {"render-on-items", "inventory-only"}));
        modules.add(new EntityESP());
        modules.add(new DumpModule("fakeplayer", "FakePlayer", Category.VISUAL, "world", "KDFzREm.TP", 54, new String[] {}));
        modules.add(new DumpModule("fog", "Fog", Category.VISUAL, "world", "KDFzREm.bm", 34, new String[] {}));
        modules.add(new DumpModule("freelook", "FreeLook", Category.VISUAL, "world", "KDFzREm.bG", 28, new String[] {}));
        modules.add(new DumpModule("gps", "GPS", Category.VISUAL, "", "KDFzREm.bw", 40, new String[] {"target-x", "target-z", "clear-target"}));
        modules.add(new Gamma());
        modules.add(new DumpModule("hands", "Hands", Category.VISUAL, "world", "KDFzREm.bk", 29, new String[] {"color-right", "color-left", "texture-mix"}));
        modules.add(new DumpModule("hotkeys", "Hotkeys", Category.VISUAL, "", "KDFzREm.jq", 9, new String[] {}));
        modules.add(new DumpModule("inventory", "Inventory", Category.VISUAL, "", "KDFzREm.jK", 9, new String[] {}));
        modules.add(new DumpModule("jumpeffect", "JumpEffect", Category.VISUAL, "world", "KDFzREm.Tb", 37, new String[] {"wave-amplitude", "first-color", "second-color"}));
        modules.add(new DumpModule("killeffect", "KillEffect", Category.VISUAL, "world", "KDFzREm.bQ", 47, new String[] {"behind-walls"}));
        modules.add(new DumpModule("logo", "Logo", Category.VISUAL, "", "KDFzREm.jV", 42, new String[] {}));
        modules.add(new DumpModule("notifications", "Notifications", Category.VISUAL, "", "KDFzREm.jc", 29, new String[] {"module-toggle", "armor-durability", "irc-ping"}));
        modules.add(new DumpModule("particles", "Particles", Category.VISUAL, "world", "KDFzREm.bK", 49, new String[] {"totem-popping", "thrown-item", "critical-hit", "color-selectable", "color-range"}));
        modules.add(new DumpModule("potions", "Potions", Category.VISUAL, "", "KDFzREm.je", 10, new String[] {}));
        modules.add(new DumpModule("predictions", "Predictions", Category.VISUAL, "world", "KDFzREm.bx", 40, new String[] {"predict-entity", "line-color"}));
        modules.add(new DumpModule("removals", "Removals", Category.VISUAL, "screen", "KDFzREm.ji", 62, new String[] {"tilt-view", "vignette-overlay", "fire-overlay", "under-water-overlay", "wall-overlay", "totem-pop", "status-effect-overlay", "camera-clip", "heart-effect", "fishing-bobber", "wither-spawn", "end-portal-open", "anarchy-events", "exp-bottle", "sound-multiplier"}));
        modules.add(new DumpModule("saturation", "Saturation", Category.VISUAL, "world", "KDFzREm.Tt", 30, new String[] {}));
        modules.add(new SeeInvisible());
        modules.add(new DumpModule("shulkerpreview", "ShulkerPreview", Category.VISUAL, "screen", "KDFzREm.Tl", 43, new String[] {"show-in-world"}));
        modules.add(new DumpModule("skycustomization", "SkyCustomization", Category.VISUAL, "world", "KDFzREm.jW", 56, new String[] {"aurora-first", "aurora-second"}));
        modules.add(new DumpModule("streamermode", "StreamerMode", Category.VISUAL, "screen", "KDFzREm.js", 63, new String[] {"hide-entries", "custom-name"}));
        modules.add(new DumpModule("swinganimations", "SwingAnimations", Category.VISUAL, "world", "KDFzREm.jG", 35, new String[] {"swing-1", "swing-2", "swing-3", "swing-4", "swing-strength", "spin-smoothness", "only-while-have-target"}));
        modules.add(new TargetEsp());
        modules.add(new DumpModule("targetinfo", "TargetInfo", Category.VISUAL, "", "KDFzREm.jH", 26, new String[] {"show-from-mouse", "show-armor-details", "show-absorption"}));
        modules.add(new TimeChanger());
        modules.add(new DumpModule("tracers", "Tracers", Category.VISUAL, "screen", "KDFzREm.jQ", 23, new String[] {}));
        modules.add(new DumpModule("trajectory", "Trajectory", Category.VISUAL, "world", "KDFzREm.bh", 48, new String[] {"predict-entity", "line-color", "hit-line-color"}));
        modules.add(new DumpModule("viewmodel", "ViewModel", Category.VISUAL, "world", "KDFzREm.TY", 27, new String[] {"right-hand-x", "right-hand-y", "right-hand-z", "right-scale", "left-hand-x", "left-hand-y", "left-hand-z", "left-scale"}));
        modules.add(new DumpModule("anarchyhelper", "AnarchyHelper", Category.MISC, "helper", "KDFzREm.mZ", 57, new String[] {"god-aura", "sheer-dust", "holy-water", "potion-holy-water", "potion-rage", "potion-paladin", "potion-assassin", "potion-drowsiness", "potion-radiation"}));
        modules.add(new DumpModule("auctionhelper", "AuctionHelper", Category.MISC, "helper", "KDFzREm.mc", 77, new String[] {"profitable-color", "profitable-items-count", "open-auction-from-item", "show-item-price"}));
        modules.add(new DumpModule("autobuy", "AutoBuy", Category.MISC, "base", "KDFzREm.WV", 50, new String[] {"decrease-prices", "auto-parser"}));
        modules.add(new DumpModule("bypasshealth", "BypassHealth", Category.MISC, "base", "KDFzREm.Ww", 8, new String[] {}));
        modules.add(new DumpModule("chathelper", "ChatHelper", Category.MISC, "helper", "KDFzREm.ma", 24, new String[] {"better-commands", "chat-addons"}));
        modules.add(new DumpModule("clickaction", "ClickAction", Category.MISC, "base", "KDFzREm.Wr", 16, new String[] {}));
        modules.add(new DumpModule("clientsounds", "ClientSounds", Category.MISC, "", "KDFzREm.Wk", 54, new String[] {"toggle-sounds", "sound-type", "select-enable-sound", "select-disable-sound", "sound-does-not-exist", "error-please-report"}));
        modules.add(new DumpModule("customcape", "CustomCape", Category.MISC, "", "KDFzREm.WY", 18, new String[] {}));
        modules.add(new DeathCoords());
        modules.add(new DumpModule("discordactivity", "DiscordActivity", Category.MISC, "", "KDFzREm.mu", 10, new String[] {}));
        modules.add(new DumpModule("elytrahelper", "ElytraHelper", Category.MISC, "helper", "KDFzREm.WO", 41, new String[] {"swap-key", "firework-key", "only-space", "auto-launch"}));
        modules.add(new DumpModule("holyhelper", "HolyHelper", Category.MISC, "helper", "KDFzREm.mO", 38, new String[] {"explosive-stuff", "exp-bottle", "explosive-trap", "snow-ball", "show-stun-zone", "zone-color"}));
        modules.add(new DumpModule("irc", "IRC", Category.MISC, "", "KDFzREm.Wg", 8, new String[] {}));
        modules.add(new DumpModule("openwalls", "OpenWalls", Category.MISC, "base", "KDFzREm.WI", 13, new String[] {}));
        modules.add(new DumpModule("potiontracker", "PotionTracker", Category.MISC, "trackers", "KDFzREm.WJ", 43, new String[] {"ignore-self", "ignore-common-splash-potions", "ft-bypass"}));
        modules.add(new DumpModule("srpspoofer", "SRPSpoofer", Category.MISC, "base", "KDFzREm.Wq", 9, new String[] {}));
        modules.add(new DumpModule("tickratesync", "TickRateSync", Category.MISC, "base", "KDFzREm.WK", 11, new String[] {}));
        modules.add(new DumpModule("usetracker", "UseTracker", Category.MISC, "trackers", "KDFzREm.mA", 24, new String[] {"totem-tracker", "food-tracker"}));
    }

    private GeneratedModules() {}
}
