org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.parallel=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
kotlin.jvm.target.validation.mode=warning
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
kotlin.jvm.target.validation.mode=warning
